version: '3.9'

services:
        db:
          image: mongo
          container_name: db
          restart: always
          environment: 
            - MONGO_INTDB_ROOT_USERNAME-dio
            - MONGO_INTDB_ROOT_PASSWORD=dio
          ports:
            - "27017:27017"
          volumes:
            - ./dbdata:/data/db
            